name: npm-publish

on:
  push:
    branches:
      - master
    paths:
      - 'package.json'
      - 'src/*.js'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://registry.npmjs.org/
      - name: Clean install
        run: npm ci
      - name: Build with rollup
        run: npm run build
      # - name: Publish latest version
      #   run: npm publish
      - name: Check steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
