name: npm-publish

on:
  push:
    branches:
      - master
      - feature/check-version

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://registry.npmjs.org/
      - name: Clean install
        run: npm ci
      - name: Build with rollup
        run: npm run build
      - name: Publish latest version
        run: echo "$PUBLISHED_VERSION" && echo "$PKG_VERSION"
        env:
          PUBLISHED_VERSION: ${{ node -p "require('./package.json').version" }}
          PKG_VERSION: ${{ npm view @domtwlee/redux-api-actions version }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
